server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/imagegallery
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    #    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
  liquibase:
    change-log: classpath:db.changelog/changelog-master.xml